language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
android:
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
 components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
before_script:
    # Prepare pre-accepted licenses to not be promted at installation
    - mkdir -p "$ANDROID_HOME/licenses"
script:
    - ./gradlew build check
notifications:
  email: false